# path to the the preprocess file with the text to elaborate.
# required: True
preproc_file = "nlp-nocera_preproc.csv"
# path to the file with the classified terms.
# required: True
terms_file = "nlp-nocera_terms.csv"
# path to the directory where to save the results.
# required: False
outdir = "."
# Column in preproc_file to process. If omitted 'abstract_lem' is used.
# required: False
text-column = "abstract_lem"
# Column in preproc_file to use as document title. If omitted 'title' is used.
# required: False
title-column = "title"
# Minimum number of topics to retrieve (default: 5)
# required: False
min-topics = 5
# Maximum number of topics to retrieve (default: 20)
# required: False
max-topics = 20
# Step in range(min,max,step) for topics retrieving (default: 1)
# required: False
step-topics = 1
# Seed to be used in training
# required: False
seed = ""
# if set, it plots the coherence
# required: False
plot-show = false
# if set, it saves the plot of the coherence as <outdir>/lda_plot.pdf
# required: False
plot-save = false
# Placeholder for barrier word. Also used as a prefix for the relevant words. Default: @
# required: False
placeholder = "@"
# Delimiter used in preproc_file. Default '\t'
# required: False
delimiter = "\t"
